# Generated by Django 5.1.4 on 2025-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country code (ej: +34)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Number phone (ej: +34600000000)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_national',
            field=models.CharField(blank=True, help_text='Phone number without country code (ej: 600000000)', max_length=15, null=True),
        ),
    ]
