# Generated by Django 5.1.4 on 2025-03-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='+57', help_text='Country code (ej: +34)', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='3123456789', help_text='Number phone (ej: +34600000000)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_national',
            field=models.CharField(blank=True, default='+573123456789', help_text='Phone number without country code (ej: 600000000)', max_length=15, null=True),
        ),
    ]
