# Generated by Django 5.1.4 on 2025-03-08 01:06

import Documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0001_initial'),
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('document_pdf', models.FileField(upload_to='Documents/files/', validators=[Documents.models.validate_pdf])),
                ('document_hash_previous', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('issued_date', models.DateField()),
                ('unique_identifier', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('copy_id', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
    ]
