# Generated by Django 5.1.4 on 2025-03-08 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documents', '0001_initial'),
        ('Employment_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_hash', models.CharField(max_length=64, unique=True)),
                ('issued_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='Documents.document')),
                ('employment_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_copies', to='Employment_history.employmenthistory')),
            ],
            options={
                'verbose_name': 'Document Copy',
                'verbose_name_plural': 'Document Copies',
                'ordering': ['-issued_date'],
            },
        ),
    ]
