# Generated by Django 5.1.4 on 2025-03-08 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(default='Unknow', max_length=100)),
                ('start_date', models.DateField(default='2000-01-01')),
                ('end_date', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('department', models.CharField(choices=[('Direccion y Administracion General', 'Dirección y Administración General'), ('Recursos Humanos', 'Recursos Humanos'), ('Finanzas y Contabilidad', 'Finanzas y Contabilidad'), ('Operaciones', 'Operaciones'), ('Comercial y Ventas', 'Comercial y Ventas'), ('Marketing y Publicidad', 'Marketing y Publicidad'), ('Tecnologias de la Informacion', 'Tecnologías de la Información (TI)'), ('Innovacion e Investigacion', 'Innovación e Investigación'), ('Compras y Proveedores', 'Compras y Proveedores'), ('Juridico y Cumplimiento', 'Jurídico y Cumplimiento'), ('Responsabilidad Social y Sostenibilidad', 'Responsabilidad Social y Sostenibilidad'), ('Seguridad y Gestion de Riesgos', 'Seguridad y Gestión de Riesgos'), ('Servicio al Cliente', 'Servicio al Cliente'), ('Investigacion y Desarrollo', 'Investigación y Desarrollo (I+D)'), ('Relaciones Institucionales', 'Relaciones Institucionales'), ('Otros', 'Otros')], default='Otros', max_length=100)),
                ('subcategory', models.CharField(default='Otros', max_length=100)),
                ('employment_history_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('current_company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='Employees.employee')),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment Histories',
                'ordering': ['-start_date'],
            },
        ),
    ]
